language: java

env:
  - TRAVIS_NODE_VERSION=6
  - TRAVIS_NODE_VERSION=iojs
jdk:
  - oraclejdk8

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch restart
  - nvm install "$TRAVIS_NODE_VERSION"
  - nvm use "$TRAVIS_NODE_VERSION"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
 - yarn install

script:
 - npm test
